// Municipality configuration
// To add a new municipality, just add an entry to the appropriate array.
// platform: 'bidsandtenders' | 'biddingo' | 'municipal'

export const BIDSANDTENDERS_SOURCES = [
  { id: 'lanark-county',        name: 'County of Lanark',                        subdomain: 'lanarkcounty' },
  { id: 'renfrew-county',       name: 'County of Renfrew',                       subdomain: 'countyofrenfrew' },
  { id: 'leeds-grenville',      name: 'United Counties of Leeds & Grenville',    subdomain: 'leedsgrenville' },
  { id: 'prescott-russell',     name: 'United Counties of Prescott & Russell',   subdomain: 'prescott-russell' },
  { id: 'smiths-falls',         name: 'Town of Smiths Falls',                    subdomain: 'smithsfalls' },
  { id: 'casselman',            name: 'Municipality of Casselman',               subdomain: 'casselman' },
  { id: 'clarence-rockland',    name: 'City of Clarence-Rockland',               subdomain: 'clarence-rockland' },
  { id: 'leeds-1000-islands',   name: 'Township of Leeds and the Thousand Islands', subdomain: 'leeds1000islands' },
  { id: 'frontenac-islands',    name: 'Township of Frontenac Islands',           subdomain: 'frontenacislands' },
  { id: 'utilities-kingston',   name: 'Utilities Kingston',                      subdomain: 'utilitieskingston' },
  { id: 'cornwall',             name: 'City of Cornwall',                        subdomain: 'cornwall' },
  { id: 'canoe',                name: 'Canoe Procurement Group',                 subdomain: 'canoe' },
  { id: 'nation-municipality',  name: 'The Nation Municipality',                 subdomain: 'nationmunicipality' },
  { id: 'alfred-plantagenet',   name: 'Township of Alfred-Plantagenet',          subdomain: 'alfredplantagenet' },
];

export const BIDDINGO_SOURCES = [
  { id: 'kingston',             name: 'City of Kingston',           path: 'kingston' },
  { id: 'south-frontenac',      name: 'Township of South Frontenac', path: 'southfrontenac' },
];

export const MUNICIPAL_SOURCES = [
  {
    id: 'ottawa',
    name: 'City of Ottawa',
    url: 'https://ottawa.ca/en/city-hall/procurement-and-contracts/solicitations-and-awards',
    tendersSelector: '.views-row',
    titleSelector: '.views-field-title a',
    dateSelector: '.views-field-field-closing-date',
    linkBase: 'https://ottawa.ca',
  },
  {
    id: 'mississippi-mills',
    name: 'Town of Mississippi Mills (Almonte)',
    url: 'https://www.mississippimills.ca/en/business/tenders-and-rfps.aspx',
    tendersSelector: '.accordionButton, .field-items .field-item, li',
    titleSelector: 'a',
    dateSelector: null,
    linkBase: 'https://www.mississippimills.ca',
  },
  {
    id: 'carleton-place',
    name: 'Town of Carleton Place',
    url: 'https://www.carletonplace.ca/en/business/tenders.aspx',
    tendersSelector: '.field-items .field-item, li',
    titleSelector: 'a',
    dateSelector: null,
    linkBase: 'https://www.carletonplace.ca',
  },
  {
    id: 'arnprior',
    name: 'Town of Arnprior',
    url: 'https://www.arnprior.ca/en/business/tenders.aspx',
    tendersSelector: '.field-items .field-item, li',
    titleSelector: 'a',
    dateSelector: null,
    linkBase: 'https://www.arnprior.ca',
  },
  {
    id: 'pembroke',
    name: 'City of Pembroke',
    url: 'https://www.pembroke.ca/en/business/bids-and-tenders.aspx',
    tendersSelector: 'li, .field-item',
    titleSelector: 'a',
    dateSelector: null,
    linkBase: 'https://www.pembroke.ca',
  },
  {
    id: 'renfrew',
    name: 'Town of Renfrew',
    url: 'https://www.renfrew.ca/en/business/tenders.aspx',
    tendersSelector: 'li, .field-item',
    titleSelector: 'a',
    dateSelector: null,
    linkBase: 'https://www.renfrew.ca',
  },
  {
    id: 'petawawa',
    name: 'Town of Petawawa',
    url: 'https://www.petawawa.ca/en/business/bids-and-tenders.aspx',
    tendersSelector: 'li, .field-item',
    titleSelector: 'a',
    dateSelector: null,
    linkBase: 'https://www.petawawa.ca',
  },
  {
    id: 'laurentian-hills',
    name: 'Town of Laurentian Hills',
    url: 'https://www.laurentianhills.ca/en/business/tenders.aspx',
    tendersSelector: 'li, .field-item',
    titleSelector: 'a',
    dateSelector: null,
    linkBase: 'https://www.laurentianhills.ca',
  },
  {
    id: 'perth',
    name: 'Town of Perth',
    url: 'https://www.perth.ca/en/business/tenders.aspx',
    tendersSelector: 'li, .field-item',
    titleSelector: 'a',
    dateSelector: null,
    linkBase: 'https://www.perth.ca',
  },
  {
    id: 'north-grenville',
    name: 'Municipality of North Grenville',
    url: 'https://www.northgrenville.ca/en/business/tenders.aspx',
    tendersSelector: 'li, .field-item',
    titleSelector: 'a',
    dateSelector: null,
    linkBase: 'https://www.northgrenville.ca',
  },
  {
    id: 'lanark-highlands',
    name: 'Township of Lanark Highlands',
    url: 'https://www.lanarkhighlands.ca/en/business/tenders.aspx',
    tendersSelector: 'li, .field-item',
    titleSelector: 'a',
    dateSelector: null,
    linkBase: 'https://www.lanarkhighlands.ca',
  },
  {
    id: 'champlain',
    name: 'Champlain Township',
    url: 'https://www.champlain.ca/en/business/tenders.aspx',
    tendersSelector: 'li, .field-item',
    titleSelector: 'a',
    dateSelector: null,
    linkBase: 'https://www.champlain.ca',
  },
  {
    id: 'beckwith',
    name: 'Township of Beckwith',
    url: 'https://www.beckwith.ca/en/business/tenders.aspx',
    tendersSelector: 'li, .field-item',
    titleSelector: 'a',
    dateSelector: null,
    linkBase: 'https://www.beckwith.ca',
  },
  {
    id: 'montague',
    name: 'Township of Montague',
    url: 'https://www.montaguetownship.ca/en/business/tenders.aspx',
    tendersSelector: 'li, .field-item',
    titleSelector: 'a',
    dateSelector: null,
    linkBase: 'https://www.montaguetownship.ca',
  },
  {
    id: 'merrickville-wolford',
    name: 'Village of Merrickville-Wolford',
    url: 'https://www.merrickville-wolford.ca/en/business/tenders.aspx',
    tendersSelector: 'li, .field-item',
    titleSelector: 'a',
    dateSelector: null,
    linkBase: 'https://www.merrickville-wolford.ca',
  },
  {
    id: 'gananoque',
    name: 'Town of Gananoque',
    url: 'https://www.gananoque.ca/en/business/tenders.aspx',
    tendersSelector: 'li, .field-item',
    titleSelector: 'a',
    dateSelector: null,
    linkBase: 'https://www.gananoque.ca',
  },
  {
    id: 'frontenac-county',
    name: 'County of Frontenac',
    url: 'https://www.frontenaccounty.ca/en/business/tenders.aspx',
    tendersSelector: 'li, .field-item',
    titleSelector: 'a',
    dateSelector: null,
    linkBase: 'https://www.frontenaccounty.ca',
  },
];
